# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: my-Class3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: 12    
          
          # installing surge       
     - name: Deploy Surge
        run: npm install --global surge 
        - name: Deploying using surge
      run:   surge ./ http://my-class3amjad.surge.sh --token ${{ secrets.SURGE_TOCKEN }}
